const cities = [
  'Abilene - Sweetwater',
  'Albany, NY',
  'Schenectady, NY',
  'Troy, NY',
  'Albany, GA',
  'Albuquerque, NM',
  'Santa Fe, NM',
  'Alexandria, LA',
  'Alpena, MI',
  'Amarillo, TX',
  'Anchorage, AK',
  'Atlanta, GA',
  'Augusta, GA',
  'Austin, TX',
  'Bakersfield, CA',
  'Baltimore, MD',
  'Bangor, ME',
  'Baton Rouge, LA',
  'Beaumont, TX',
  'Port Arthur, TX',
  'Bend, OR',
  'Billings, MT',
  'Biloxi, MS',
  'Gulfport, MS',
  'Binghamton, NY',
  'Birmingham, AL',
  'Anniston, AL',
  'Tuscaloosa, AL',
  'Bluefield, WV',
  'Beckley, WV',
  'Oak Hill, WV',
  'Boise, ID',
  'Boston, MA',
  'Manchester, MA',
  'Bowling Green, KY',
  'Buffalo, NY',
  'Burlington, MA',
  'Plattsburgh, MA',
  'Butte, MT',
  'Bozeman, MT',
  'Casper, WY',
  'Riverton, WY',
  'Cedar Rapids, IA',
  'Waterloo, IA',
  'Champaign, IL',
  'Springfield, IL',
  'Decatur, IL',
  'Charleston, SC',
  'Charleston, WV',
  'Huntington, WV',
  'Charlotte, NC',
  'Charlottesville, VA',
  'Chattanooga, TN',
  'Cheyenne, WY',
  'Scottsbluff, WY',
  'Chicago, IL',
  'Chico, CA',
  'Redding, CA',
  'Cincinnati, OH',
  'Clarksburg, WV',
  'Weston, WV',
  'Cleveland, OH',
  'Colorado Springs, CO',
  'Pueblo, CO',
  'Columbia, MO',
  'Jefferson City, MO',
  'Columbia, SC',
  'Columbus, MS',
  'West Point, MS',
  'Tupelo, MS',
  'Columbus, GA',
  'Columbus, OH',
  'Corpus Christi, TX',
  'Dallas, TX',
  'Fort Worth, TX',
  'Davenport, IA',
  'Moline, IA',
  'Rock Island, IA',
  'Dayton, OH',
  'Denver, CO',
  'Des Moines, IA',
  'Ames, IA',
  'Detroit, MI',
  'Dothan, AL',
  'Duluth, MN',
  'Superior, MN',
  'El Paso, TX',
  'Elmira, NY',
  'Erie, PA',
  'Eugene, OR',
  'Eureka, CA',
  'Evansville',
  'Fairbanks, AK',
  'Fargo, ND',
  'Valley City, ND',
  'Flint, MI',
  'Bay City, MI',
  'Saginaw, MI',
  'Florence, SC',
  'Myrtle Beach, SC',
  'Fort Myers, FL',
  'Naples, FL',
  'Fort Smith, AR',
  'Rogers, AR',
  'Springdale, AR',
  'Fayetteville, AR',
  'Fort Wayne, IN',
  'Fresno, CA',
  'Visalia, CA',
  'Glendive, MT',
  'Grand Junction, CO',
  'Montrose, CO',
  'Grand Rapids, MI',
  'Kalamazoo, MI',
  'Battle Creek, MI',
  'Great Falls',
  'Green Bay, WI', 
  'Appleton, WI',
  'Greensboro, NC', 
  'High Point, NC', 
  'Winston-Salem, NC',
  'Greenville, NC', 
  'New Bern, NC', 
  'Washington, NC',
  'Greenville, PA',
  'Spartansburg, PA', 
  'Asheville, PA',
  'Anderson, PA',
  'Greenwood, SC',
  'Greenville, SC',
  'Harlingen, TX',
  'Weslaco, TX',
  'Brownsville, TX',
  'McAllen, TX',
  'Harrisburg, OH',
  'Lancaster, OH',
  'Lebanon,OH',
  'York, OH',
  'Harrisonburg, VA',
  'Hartford, CT',
  'New Haven, CT',
  'Hattiesburg, MS',
  'Laurel, MS',
  'Helena, MT',
  'Honolulu, HI',
  'Houston, TX',
  'Huntsville, AL',
  'Idaho Falls, ID',
  'Pocatello, ID',
  'Indianapolis, IN',
  'Jackson, MS',
  'Jackson, TN',
  'Jacksonville, FL',
  'Johnstown, PA',
  'Altoona, PA',
  'Jonesboro, AR',
  'Joplin, MO',
  'Juneau, AK',
  'Kansas City, MO',
  'Knoxville, TN',
  'La Crosse, WI',
  'Eau Claire, WI',
  'Lafayette, IN',
  'Lafayette, LA',
  'Lake Charles, LA',
  'Lansing, MI',
  'Laredo, TX',
  'Las Vegas, NV',
  'Lexington, KY',
  'Lima, OH',
  'Lincoln, NE',
  'Hastings, NE',
  'Kearney, NE',
  'Little Rock, AR',
  'Pine Bluff, AR',
  'Los Angeles, CA',
  'Louisville, KY',
  'Lubbock, TX',
  'Macon, GA',
  'Madison, WI',
  'Mankato, MN',
  'Marquette, WI',
  'Medford, OR',
  'Klamath Falls, OR',
  'Memphis, TN',
  'Meridian, LA',
  'Miami, FL',
  'Fort Lauderdale, FL',
  'Milwaukee, MN',
  'Minneapolis, MN',
  'Saint Paul, MN',
  'Minot, ND',
  'Bismarck, ND',
  'Dickinson, ND',
  'Missoula, MT',
  'Mobile, FL',
  'Pensacola, FL',
  'Monroe, LA',
  'El Dorado, AR',
  'Monterey, CA',
  'Salinas, CA',
  'Montgomery, GA',
  'Nashville, TN',
  'New Orleans, LA',
  'New York City, NY',
  'Norfolk, VA',
  'Portsmouth, VA', 
  'Newport News, VA',
  'North Platte, NE',
  'Odessa, TX',
  'Midland, TX',
  'Oklahoma City, OK',
  'Omaha, NE',
  'Orlando, FL',
  'Daytona Beach, FL',
  'Melbourne, FL',
  'Ottumwa, IA',
  'Kirksville, IA',
  'Paducah, KY',
  'Cape Girardeau, MO',
  'Harrisburg, PA',
  'Palm Springs, CA',
  'Panama City, FL',
  'Parkersburg, WV',
  'Peoria, IL',
  'Bloomington, IL',
  'Philadelphia, PA',
  'Phoenix, AZ',
  'Pittsburgh, PA',
  'Portland, ME',
  'Auburn, ME',
  'Portland, OR',
  'Presque Isle, ME',
  'Providence, RI',
  'New Bedford, RI',
  'Quincy, IA', 
  'Hannibal, MO', 
  'Keokuk, IA',
  'Raleigh, NC',
  'Durham, NC',
  'Rapid City, SD',
  'Reno, NV',
  'Richmond, VA',
  'Petersburg, VA',
  'Lynchburg, Va',
  'Rochester, MN',
  'Mason City, IA',
  'Austin, MN',
  'Rochester, NY',
  'Rockford, IL',
  'Sacramento, CA',
  'Stockton, CA',
  'Modesto, CA',
  'Saint Joseph, MO',
  'Saint Louis, MO',
  'Salisbury, MD',
  'Salt Lake City, UT',
  'San Angelo, TX',
  'San Antonio, TX',
  'San Diego, CA',
  'San Francisco, CA',
  'Oakland, CA',
  'San Jose, CA',
  'Santa Barbara, CA',
  'Santa Maria, CA',
  'San Luis Obispo, CA',
  'Savannah, GA',
  'Seattle, WA',
  'Tacoma, WA',
  'Sherman, TX',
  'Ada, TX',
  'Shreveport, LA',
  'Sioux City, IA',
  'Sioux Falls, SD',
  'South Bend, IN',
  'Elkhart, IN',
  'Spokane, KS',
  'Springfield, MS',
  'Holyoke, MS',
  'Springfield, MO',
  'Syracuse, NY',
  'Tallahassee, FL',
  'Thomasville, FL',
  'Tampa,FL',
  'Saint Petersburg, FL',
  'Terre Haute, IN',
  'Toledo, OH',
  'Topeka, KS',
  'Traverse City, MI',
  'Cadillac, MI',
  'Tucson, AZ',
  'Tulsa, OK',
  'Twin Falls, ID',
  'Tyler, TX',
  'Longview, TX',
  'Utica, NY',
  'Victoria, TX',
  'Waco, TX',
  'Temple, TX',
  'Bryan, TX',
  'Washington DC',
  'Watertown, NY',
  'Wausau, WI',
  'Rhinelander, WI',
  'West Palm Beach, FL',
  'Fort Pierce, FL',
  'Wheeling - Steubenville',
  'Wichita - Hutchinson',
  'Wichita Falls & Lawton',
  'Wilkes Barre - Scranton',
  'Wilmington',
  'Yakima - Pasco - Richland - Kennewick',
  'Youngstown',
  'Yuma - El Centro',
  'Zanesville',
];

export default cities;